name: 'Deploy Binaries'
on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'Build & Deploy'
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch:
          - x64
          - arm64

        node-version:
          - node16

        os:
          - linux
          - macos
          - win

    steps:
      - name: Package into node binary
        uses: lando/pkg-action@v2
        with:
          entrypoint: index.js
          arch: ${{ matrix.arch }}
          node-version: ${{ matrix.node-version }}
          os: ${{ matrix.os }}